kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql2-pvc
spec:
  storageClassName: longhorn-storage-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
