apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pod-nfs-delete-replicaset
spec:
  replicas: 1 # Desired number of pods
  selector:
    matchLabels:
      app: pod-nfs-delete # Matches the Pod's label
  template: # Pod template (identical to your provided spec)
    metadata:
      labels:
        app: pod-nfs-delete 
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: test-pvc-delete
