apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-retain
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce # Adjust access modes as needed (e.g., ReadWriteOnce)
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nttung-nfs-retain
  mountOptions:
    # Add mount options for your NFS configuration if needed
  nfs:
    path: /data2/retain
    server: 192.168.41.22
