kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc-delete
spec:
  storageClassName: nttung-nfs-delete
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
